# Generated by Django 3.0.6 on 2020-06-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=130)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=10000)),
                ('image', models.ImageField(default='', upload_to='Blog/images')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
