# Generated by Django 3.0.6 on 2020-06-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPosts',
            new_name='Post',
        ),
    ]
