# Generated by Django 3.0.6 on 2020-06-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='phone',
        ),
    ]
