# Generated by Django 3.0.6 on 2020-07-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_htmlchapters_htmldescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='csschapters',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='djchapters',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jschapters',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pychapters',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pydescription',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.htmlchapters')),
            ],
        ),
        migrations.CreateModel(
            name='jsdescription',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.htmlchapters')),
            ],
        ),
        migrations.CreateModel(
            name='djdescription',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.htmlchapters')),
            ],
        ),
        migrations.CreateModel(
            name='cssdescription',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.htmlchapters')),
            ],
        ),
    ]
