# Generated by Django 3.0.6 on 2020-07-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_csschapters_cssdescription_djchapters_djdescription_jschapters_jsdescription_pychapters_pydescriptio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssdescription',
            name='chapters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.csschapters'),
        ),
        migrations.AlterField(
            model_name='djdescription',
            name='chapters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.djchapters'),
        ),
        migrations.AlterField(
            model_name='jsdescription',
            name='chapters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jschapters'),
        ),
        migrations.AlterField(
            model_name='pydescription',
            name='chapters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pychapters'),
        ),
    ]
